# Generated by Django 3.2.4 on 2021-07-31 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcorpus',
            name='schemaText',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
