# Generated by Django 3.2.5 on 2021-08-01 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_trainingcorpus_schematext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingcorpus',
            name='schemaText',
        ),
    ]
