# Generated by Django 3.2.5 on 2021-08-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_remove_trainingcorpus_schematext'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptinputoutput',
            name='userId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='userId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdatabaseentity',
            name='userId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
